image:
  name: python:3.8

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
  - .cache/pip
  - .venv

stages:
- deploy
- quality
- tests


# Jobs templates
# --------------

.quality-template: &quality
  stage: quality
  interruptible: true
  before_script:
  - pip install pre-commit
  - pre-commit install

.unit-test-template: &unit-test
  stage: tests
  interruptible: true
  coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
  before_script:
  - apt-get update
  - apt-get install -y libportaudio2 libsndfile1
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv
  script:
  - poetry run pytest --showlocals


# Quality jobs
# ------------

pre-commits:
  <<: *quality
  script: pre-commit run --all-files


# Unit tests jobs
# ---------------

unit-tests/3.8:
  <<: *unit-test
  image: python:3.8
  coverage: '/^TOTAL.+?(\d+\%)$/'

unit-tests/3.9:
  <<: *unit-test
  image: python:3.9

unit-tests/3.10:
  <<: *unit-test
  image: python:3.10

unit-tests/missing backends:
  <<: *unit-test
  script:
  # no ipython
  - poetry run pip uninstall --yes ipython
  - poetry run pytest --showlocals

  # no Port Audio backend
  - apt-get remove -y libportaudio2
  - poetry run pytest --showlocals

pages:
  stage: deploy
  before_script:
  - pip install -r docs/requirements.txt
  script:
  - mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
