site_name: sonoUno Library
repo_name: pchanial/sonouno-library
repo_url: https://gitlab.com/pchanial/sonouno-library

theme:
  name: material

nav:
- index.md
- getting_started.md
- contributing.md
- API: mkapi/api/sonounolib

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- markdown_include.include:
    base_path: examples
- toc:
    permalink: True
- admonition

plugins:
- search
- mkapi:
    src_dirs:
    - sonounolib
- exclude:
    glob:
    - requirements.txt
